<?php

/**
 * Variable initial definitions
 */
$id              = $name              = $email              = $message              = null;
$image           = $ratings           = null;
$selected_0_attr = $selected_1_attr = $selected_2_attr = $selected_3_attr = $selected_4_attr = null;
$selected_4_attr = $selected_5_attr = null;

/**
 * Set collection data into variables
 */
$collectionData = $block->getResult();
if ($collectionData) {
    foreach ($collectionData as $ky => $val) {
        ${$ky} = $val;
    }
}

switch ($ratings) {
    case 1:
        $selected_1_attr = 'selected';
        break;
    case 2:
        $selected_2_attr = 'selected';
        break;
    case 3:
        $selected_3_attr = 'selected';
        break;
    case 4:
        $selected_4_attr = 'selected';
        break;
    case 5:
        $selected_5_attr = 'selected';
        break;
    default:
        $selected_0_attr = 'selected';
        break;
}

if ($image) {
    $image = "<img src='" . $block->getBaseUrl() . $image . "' alt='Testimonial Uploaded Image' title='Testimonial Uploaded Image' width='100' height='100' class='img img-thumbnail'>";
}

?>
    <h3>Submit your testimonial</h3>
    <hr>
    <form method="post"
          name="testimonial_form"
          id="testimonial_form"
          enctype="multipart/form-data"
          action="<?php echo $block->getUrl('testimonial/index/save'); ?>"
          class="form"
          data-hasrequired="<?=$block->escapeHtmlAttr(__('* Required Fields'));?>"
          data-mage-init='{"validation":{}}'>

        <input type="hidden" name="id" value="<?php echo $id; ?>">

        <fieldset class="fieldset">
            <div class="field name required">
                <label class="label" for="name"><span><?php echo $block->escapeHtml(__('Name')); ?></span></label>
                <div class="control">
                    <input name="name" id="name"
                           title="<?php echo $block->escapeHtmlAttr(__('Name')); ?>"
                           class="input-text" type="text"
                           data-validate="{required:true}"
                           value="<?php echo $name; ?>">
                </div>
            </div>

            <div class="field email required">
                <label class="label" for="email"><span><?php echo $block->escapeHtml(__('Email')); ?></span></label>
                <div class="control">
                    <input name="email" id="email"
                           title="<?php echo $block->escapeHtmlAttr(__('Email')); ?>"
                           class="input-text"
                           type="email"
                           data-validate="{required:true, 'validate-email':true}"
                           value="<?php echo $email; ?>">
                </div>
            </div>

            <div class="field image">
                <label class="label" for="image"><?php echo $block->escapeHtml(__('Image')); ?></label>
                <div class="control">
                    <?php echo $image; ?>
                    <input type="file" class="form-control" name="image" id="image" accept="image/*" class="input-file">
                </div>
            </div>

            <div class="field ratings required">
                <label class="label" for="ratings"><span><?php echo $block->escapeHtml(__('Ratings')); ?></span></label><br>
                <div class="control">
                    <select name="ratings"
                            id="ratings"
                            class="select-box"
                            data-validate="{required:true}">
                        <option <?php echo $selected_0_attr; ?> value="">Select</option>
                        <option <?php echo $selected_1_attr; ?> >1</option>
                        <option <?php echo $selected_2_attr; ?> >2</option>
                        <option <?php echo $selected_3_attr; ?> >3</option>
                        <option <?php echo $selected_4_attr; ?> >4</option>
                        <option <?php echo $selected_5_attr; ?> >5</option>
                    </select>
                </div>
            </div>

            <div class="field message required">
                <label class="label" for="message"><span><?=$block->escapeHtml(__('Message'));?></span></label>
                <div class="control">
                <textarea name="message"
                          id="message"
                          title="<?php echo $block->escapeHtmlAttr(__('Message')); ?>"
                          class="input-text"
                          cols="5" rows="3"
                          data-validate="{required:true}"><?php echo $message; ?></textarea>
                </div>
            </div>

            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" title="<?php echo $block->escapeHtmlAttr(__('Submit')); ?>"
                            class="action submit primary">
                        <span><?php echo $block->escapeHtml(__('Submit')); ?></span>
                    </button>
                </div>
                <div class="default">
                    <button type="button" title="<?php echo $block->escapeHtmlAttr(__('Back to testimonials')); ?>"
                            class="action default"
                            onclick="top.location.href='<?php echo $block->getUrl('testimonial/index/listview'); ?>';">
                        <span><?php echo $block->escapeHtml(__('Back to testimonials')); ?></span>
                    </button>
                </div>
            </div>
        </fieldset>
    </form>
<?php
