<?php

// declare(strict_types=1);

// Note test_a is mapped in view/frontend/requirejs-config.js

?>
<h1 data-mage-init='{"custom_js/title": {}}'></h1>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "startSimple": {
                        "component": "Training_Testimonial/js/plain-view-model",
                        "base_url": "<?php echo $block->escapeJs($block->getBaseUrl());?>",
                        "data": "test data"
                    }
                }
            }
        }
    }
</script>

<div data-bind="scope: 'startSimple'">
    <div data-bind="text: title"></div>    
    <div data-bind="text: JSON.stringify(config.base_url, null, 2);"></div>    
    <div data-bind="text: data"></div>    
</div>

<!-- <div id="collapsibleDiv" data-mage-init='{
     "collapsible": {
        "active": true,
        "saveState": true,
        "animate": {
            "duration": 600,
            "easing": "linear"
        },
        "ajaxContent": true
      }
    }'>
    <div data-role="title">Title <button data-role="trigger">Show Content</button></div>

    <div data-role="content" id="collapsibleSampleContent"></div>

    <a href="<?php echo $block->getViewFileUrl("Training_Testimonial/example-content.html"); ?>" data-ajax="true"></a>
</div> -->

<br >
<div id="collapsibleDiv3" data-mage-init='{
     "Training_Testimonial/js/dynamic-collapsible": {
        "ajaxContent": true
      }
    }'>
    <div data-role="title">Show Content</div>

    <div data-role="content" id="collapsibleSampleContent3"></div>

    <a href="<?php echo $block->getViewFileUrl("Training_Testimonial/example-content.html"); ?>" data-ajax="true"></a>
</div>


<script type="text/x-magento-init">
    {

        "*": {
            "Training_Testimonial/js/custom-require": {}
        },

        "div#testing1": {
            "test_a": { 
                "base_url": "<?php echo $block->escapeJs($block->getBaseUrl()); ?>"
            }
        },

        "#testing2": {
            "Training_Testimonial/js/custom-requireDi": {
                "base_url": "<?php echo $block->escapeJs($block->getBaseUrl()); ?>"
            }
        }
    }
</script>
<pre id="testing2"></pre>
<div id="testing1">In</div>

