<?php

// declare(strict_types=1);

// Note test_a is mapped in view/frontend/requirejs-config.js

?>
<h1 data-mage-init='{"custom_js/title": {}}'></h1>
<script type="text/x-magento-init">
    {

        "*": {
            "Training_Testimonial/js/custom-require": {}
        },

        "div#testing1": {
            "test_a": { 
                "base_url": "<?php echo $block->escapeJs($block->getBaseUrl()); ?>"
            }
        },

        "#testing2": {
            "Training_Testimonial/js/custom-requireDi": {
                "base_url": "<?php echo $block->escapeJs($block->getBaseUrl()); ?>"
            }
        }
    }
</script>
<div id="testing1">In</div>
<pre id="testing2"></pre>
