<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Shipping\Block\Items */ ?>
<?php  $_order = $block->getOrder() ?>
<?php foreach ($_order->getShipmentsCollection() as $_shipment): ?>
<div class="order-title">
    <strong><?= /* @escapeNotVerified */ __('Shipment #') ?><?= /* @escapeNotVerified */ $_shipment->getIncrementId() ?></strong>
    <div class="actions-toolbar">
        <?php if ($_order->getTracksCollection()->count()) : ?>
            <?= $block->getChildHtml('track-all-link') ?>
        <?php endif; ?>
        <a href="<?= /* @escapeNotVerified */ $block->getPrintAllShipmentsUrl($_order) ?>"
           onclick="this.target='_blank'"
           class="action print">
            <span><?= /* @escapeNotVerified */ __('Print All Shipments') ?></span>
        </a>
        <a href="<?= /* @escapeNotVerified */ $block->getPrintShipmentUrl($_shipment) ?>"
           onclick="this.target='_blank'"
           class="action print">
            <span><?= /* @escapeNotVerified */ __('Print Shipment') ?></span>
        </a>
        <a href="#"
           data-mage-init='{"popupWindow": {"windowURL":"<?= /* @escapeNotVerified */ $this->helper('Magento\Shipping\Helper\Data')->getTrackingPopupUrlBySalesModel($_shipment) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
           title="<?= /* @escapeNotVerified */ __('Track this shipment') ?>"
           class="action track">
            <span><?= /* @escapeNotVerified */ __('Track this shipment') ?></span>
        </a>
    </div>
</div>
<div class="table-wrapper order-items-shipment">
    <table class="data table table-order-items shipment" id="my-shipment-table-<?= /* @escapeNotVerified */ $_shipment->getId() ?>">
        <caption class="table-caption"><?= /* @escapeNotVerified */ __('Items Shipped') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?= /* @escapeNotVerified */ __('Product Name') ?></th>
                <th class="col sku"><?= /* @escapeNotVerified */ __('SKU') ?></th>
                <th class="col qty"><?= /* @escapeNotVerified */ __('Qty') ?></th>
            </tr>
        </thead>
        <?php $_items = $_shipment->getAllItems(); ?>
        <?php foreach ($_items as $_item): ?>
            <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
    </table>
</div>
<?= $block->getCommentsHtml($_shipment) ?>
<?php endforeach; ?>
