SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_entity_media_gallery_value
(
m231_studentkare.catalog_product_entity_media_gallery_value.value_id,
m231_studentkare.catalog_product_entity_media_gallery_value.store_id,
m231_studentkare.catalog_product_entity_media_gallery_value.entity_id,
m231_studentkare.catalog_product_entity_media_gallery_value.label,
m231_studentkare.catalog_product_entity_media_gallery_value.position,
m231_studentkare.catalog_product_entity_media_gallery_value.disabled,
m231_studentkare.catalog_product_entity_media_gallery_value.record_id
)
SELECT
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.value_id,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.store_id,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.row_id,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.label,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.position,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.disabled,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.record_id
FROM m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_entity_media_gallery_value.value_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.value_id,
m231_studentkare.catalog_product_entity_media_gallery_value.store_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.store_id,
m231_studentkare.catalog_product_entity_media_gallery_value.entity_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.row_id,
m231_studentkare.catalog_product_entity_media_gallery_value.label = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.label,
m231_studentkare.catalog_product_entity_media_gallery_value.position = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.position,
m231_studentkare.catalog_product_entity_media_gallery_value.disabled = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.disabled,
m231_studentkare.catalog_product_entity_media_gallery_value.record_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value.record_id;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
