SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_entity_media_gallery_value_to_entity
(
m231_studentkare.catalog_product_entity_media_gallery_value_to_entity.value_id,
m231_studentkare.catalog_product_entity_media_gallery_value_to_entity.entity_id
)
SELECT
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value_to_entity.value_id,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value_to_entity.row_id
FROM m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value_to_entity
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_entity_media_gallery_value_to_entity.value_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value_to_entity.value_id,
m231_studentkare.catalog_product_entity_media_gallery_value_to_entity.entity_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery_value_to_entity.row_id;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
