SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_index_website
(
m231_studentkare.catalog_product_index_website.website_id,
m231_studentkare.catalog_product_index_website.default_store_id,
m231_studentkare.catalog_product_index_website.website_date,
m231_studentkare.catalog_product_index_website.rate
)
SELECT
m231_studentkare_live_22112019.catalog_product_index_website.website_id,
m231_studentkare_live_22112019.catalog_product_index_website.default_store_id,
m231_studentkare_live_22112019.catalog_product_index_website.website_date,
m231_studentkare_live_22112019.catalog_product_index_website.rate
FROM m231_studentkare_live_22112019.catalog_product_index_website
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_index_website.website_id = m231_studentkare_live_22112019.catalog_product_index_website.website_id,
m231_studentkare.catalog_product_index_website.default_store_id = m231_studentkare_live_22112019.catalog_product_index_website.default_store_id,
m231_studentkare.catalog_product_index_website.website_date = m231_studentkare_live_22112019.catalog_product_index_website.website_date,
m231_studentkare.catalog_product_index_website.rate = m231_studentkare_live_22112019.catalog_product_index_website.rate;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
