SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_entity_media_gallery
(
m231_studentkare.catalog_product_entity_media_gallery.value_id,
m231_studentkare.catalog_product_entity_media_gallery.attribute_id,
m231_studentkare.catalog_product_entity_media_gallery.value,
m231_studentkare.catalog_product_entity_media_gallery.media_type,
m231_studentkare.catalog_product_entity_media_gallery.disabled
)
SELECT
m231_studentkare_live_22112019.catalog_product_entity_media_gallery.value_id,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery.attribute_id,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery.value,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery.media_type,
m231_studentkare_live_22112019.catalog_product_entity_media_gallery.disabled
FROM m231_studentkare_live_22112019.catalog_product_entity_media_gallery
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_entity_media_gallery.value_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery.value_id,
m231_studentkare.catalog_product_entity_media_gallery.attribute_id = m231_studentkare_live_22112019.catalog_product_entity_media_gallery.attribute_id,
m231_studentkare.catalog_product_entity_media_gallery.value = m231_studentkare_live_22112019.catalog_product_entity_media_gallery.value,
m231_studentkare.catalog_product_entity_media_gallery.media_type = m231_studentkare_live_22112019.catalog_product_entity_media_gallery.media_type,
m231_studentkare.catalog_product_entity_media_gallery.disabled = m231_studentkare_live_22112019.catalog_product_entity_media_gallery.disabled;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
