SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_index_eav_replica
(
m231_studentkare.catalog_product_index_eav_replica.entity_id,
m231_studentkare.catalog_product_index_eav_replica.attribute_id,
m231_studentkare.catalog_product_index_eav_replica.store_id,
m231_studentkare.catalog_product_index_eav_replica.value,
m231_studentkare.catalog_product_index_eav_replica.source_id
)
SELECT
m231_studentkare_live_22112019.catalog_product_index_eav_replica.entity_id,
m231_studentkare_live_22112019.catalog_product_index_eav_replica.attribute_id,
m231_studentkare_live_22112019.catalog_product_index_eav_replica.store_id,
m231_studentkare_live_22112019.catalog_product_index_eav_replica.value,
m231_studentkare_live_22112019.catalog_product_index_eav_replica.source_id
FROM m231_studentkare_live_22112019.catalog_product_index_eav_replica
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_index_eav_replica.entity_id = m231_studentkare_live_22112019.catalog_product_index_eav_replica.entity_id,
m231_studentkare.catalog_product_index_eav_replica.attribute_id = m231_studentkare_live_22112019.catalog_product_index_eav_replica.attribute_id,
m231_studentkare.catalog_product_index_eav_replica.store_id = m231_studentkare_live_22112019.catalog_product_index_eav_replica.store_id,
m231_studentkare.catalog_product_index_eav_replica.value = m231_studentkare_live_22112019.catalog_product_index_eav_replica.value,
m231_studentkare.catalog_product_index_eav_replica.source_id = m231_studentkare_live_22112019.catalog_product_index_eav_replica.source_id;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
