SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_index_price_replica
(
m231_studentkare.catalog_product_index_price_replica.entity_id,
m231_studentkare.catalog_product_index_price_replica.customer_group_id,
m231_studentkare.catalog_product_index_price_replica.website_id,
m231_studentkare.catalog_product_index_price_replica.tax_class_id,
m231_studentkare.catalog_product_index_price_replica.price,
m231_studentkare.catalog_product_index_price_replica.final_price,
m231_studentkare.catalog_product_index_price_replica.min_price,
m231_studentkare.catalog_product_index_price_replica.max_price,
m231_studentkare.catalog_product_index_price_replica.tier_price
)
SELECT
m231_studentkare_live_22112019.catalog_product_index_price_replica.entity_id,
m231_studentkare_live_22112019.catalog_product_index_price_replica.customer_group_id,
m231_studentkare_live_22112019.catalog_product_index_price_replica.website_id,
m231_studentkare_live_22112019.catalog_product_index_price_replica.tax_class_id,
m231_studentkare_live_22112019.catalog_product_index_price_replica.price,
m231_studentkare_live_22112019.catalog_product_index_price_replica.final_price,
m231_studentkare_live_22112019.catalog_product_index_price_replica.min_price,
m231_studentkare_live_22112019.catalog_product_index_price_replica.max_price,
m231_studentkare_live_22112019.catalog_product_index_price_replica.tier_price
FROM m231_studentkare_live_22112019.catalog_product_index_price_replica
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_index_price_replica.entity_id = m231_studentkare_live_22112019.catalog_product_index_price_replica.entity_id,
m231_studentkare.catalog_product_index_price_replica.customer_group_id = m231_studentkare_live_22112019.catalog_product_index_price_replica.customer_group_id,
m231_studentkare.catalog_product_index_price_replica.website_id = m231_studentkare_live_22112019.catalog_product_index_price_replica.website_id,
m231_studentkare.catalog_product_index_price_replica.tax_class_id = m231_studentkare_live_22112019.catalog_product_index_price_replica.tax_class_id,
m231_studentkare.catalog_product_index_price_replica.price = m231_studentkare_live_22112019.catalog_product_index_price_replica.price,
m231_studentkare.catalog_product_index_price_replica.final_price = m231_studentkare_live_22112019.catalog_product_index_price_replica.final_price,
m231_studentkare.catalog_product_index_price_replica.min_price = m231_studentkare_live_22112019.catalog_product_index_price_replica.min_price,
m231_studentkare.catalog_product_index_price_replica.max_price = m231_studentkare_live_22112019.catalog_product_index_price_replica.max_price,
m231_studentkare.catalog_product_index_price_replica.tier_price = m231_studentkare_live_22112019.catalog_product_index_price_replica.tier_price;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
