<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$ktplHelper = $this->helper('Ktpl\General\Helper\Category');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');

    if (!$_productCollection->count()) { ?>
        <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div><?php
    }else{  ?>
    
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    
    <?php
    $viewMode = 'grid';
    $imageDisplayArea = 'category_page_grid';    

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php

                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="mobile-rating-wrap">
                        <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>
                        <div class="rating-wishlist-wrap wishlist-parent-<?= $_product->getId(); ?>">
                            <a href="<?= $_product->getProductUrl() ?>#reviews" class="rating-link-wrap">
                            <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                            </a>
                            <?php
                            if ($_product->getTypeId() === \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE)
                            {
                                $childProductCollection = $_product->getTypeInstance()->getAssociatedProducts($_product);
                                $qtyOptions = array(); 
                                foreach ($childProductCollection as $ky => $item) { ?>
                                    <a href="javascript:void(0)" style="display: none;" data-post='<?php echo $wishlistHelper->getAddParams($item) ?>' class="action towishlist grouped_wishlist wishlist-link-<?= $item->getId(); ?>" data-action="add-to-wishlist"><span><?= __('Add to Wish List'); ?></span></a><?php
                                }
                            }else{ ?>
                                <a href="javascript:void(0)" data-post='<?php  echo $wishlistHelper->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span><?= __('Add to Wish List'); ?></span></a>
                            <?php } ?>
                        </div>
                    </div>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?php if($_product->getAttribute1()){ ?>
                        <div class="attribute1">
                            <?php echo __($_product->getAttribute1()); ?>
                        </div>
                        <?php } ?>

                        <?php //echo $block->getProductPrice($_product);  ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php
                                                if ($_product->getTypeId() === \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE)
                                                { ?>
                                                <div class="product-option-<?= $_product->getId() ?> options-wrap"><?php
                                                    $childProductCollection = $_product->getTypeInstance()->getAssociatedProducts($_product);
                                                    $qtyOptions = array(); ?>
                                                    <select name="grouped_options" class="grouped_options" data-productid="<?= $_product->getId() ?>">
                                                        <option value=""><?php echo __("Choose"); ?></option><?php
                                                        foreach ($childProductCollection as $key => $options) {
                                                            $options = $_subProduct = $ktplHelper->getProductById($options->getId());
                                                            $optionName = $options->getAttribute1();
                                                            $qtyOptions[$key]["qty"] = $options->getQty(); 
                                                            $qtyOptions[$key]["id"] = $options->getId();
                                                            $formattedPrice = $priceHelper->currency($options->getFinalPrice(), true, false); ?>
                                                            <option value="<?php echo $options->getId(); ?>"><?php echo $optionName." ".$formattedPrice; ?></option>><?php    
                                                        } ?>
                                                    </select><?php
                                                    echo $block->getLayout()->createBlock('Ktpl\General\Block\ProductPrice')->setProduct($_product)->setTemplate('Ktpl_General::product/price.phtml')->toHtml(); 
                                                    foreach ($qtyOptions as $key => $_item) { ?>
                                                        <div class="qty-box" id="super_group_<?= /* @escapeNotVerified */ $_item['id'] ?>" style="display: none;">  
                                                            <div class="qty">
                                                                <label><?= __("QTY"); ?></label>
                                                                <input type="number"
                                                           name="super_group[<?= /* @escapeNotVerified */ $_item['id'] ?>]"
                                                           data-selector="super_group[<?= /* @escapeNotVerified */ $_item['id'] ?>]"
                                                           id="qty_super_group_<?= /* @escapeNotVerified */ $_item['id'] ?>"
                                                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                           class="input-text qty grouped_qty"
                                                           data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                                           data-errors-message-box="#validation-message-box"/>
                                                            </div>
                                                              <button style="display: none;" type="submit"
                                                        title="<?= $block->escapeHtml(__('Add')) ?>"
                                                        class="action tocart primary grouped_btn">
                                                        <span><?= /* @escapeNotVerified */ __('Add') ?></span> 
                                                    </button>  
                                                        </div>
                                                        <?php
                                                    } ?>
                                                <input type="hidden" class="grpchild" name="grpchild" value="">  
                                                </div><?php

                                                }else{
                                                echo $block->getLayout()->createBlock('Ktpl\General\Block\ProductPrice')->setProduct($_product)->setTemplate('Ktpl_General::product/price.phtml')->toHtml(); ?>
                                                    <div class="qty-box">  
                                                        <div class="qty">
                                                            <label><?= __("QTY"); ?></label>
                                                            <input type="number" name="qty" />
                                                        </div>
                                                         <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add') ?></span> 
                                                    </button>   
                                                    </div>
                                                   
                                            <?php } ?>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            


                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
    <script type="text/javascript">
        require([
        'jquery'
        ], function ($) {
            $(document).ready(function(e){                
                $(".options-wrap .grouped_options").change(function(e){
                    var optionId = $(this).val();
                    var productId = $(this).attr("data-productid");
                    if (optionId) {
                        $(".product-option-"+productId+" .qty-box:not(#super_group_"+optionId+") .grouped_qty").val("0");
                        $("#super_group_"+optionId+" .grouped_qty").val("");
                        $(".product-option-"+productId+" .grouped_qty").parent().parent().hide();
                        $("#super_group_"+optionId).show();
                        $(".wishlist-parent-"+productId+" .grouped_wishlist").hide();
                        $(".product-option-"+productId+" .grpchild").val(optionId);
                        $(".product-option-"+productId+" .grouped_btn, .wishlist-link-"+optionId).show();
                    }else{
                        $(".product-option-"+productId+" .grpchild").val('');
                        $(".product-option-"+productId+" .qty-box, .product-option-"+productId+" .grouped_btn, .wishlist-parent-"+productId+" .grouped_wishlist").hide();
                    }
                });
            });
        });
    </script>
    <?php
}