SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_link_attribute_int
(
m231_studentkare.catalog_product_link_attribute_int.value_id,
m231_studentkare.catalog_product_link_attribute_int.product_link_attribute_id,
m231_studentkare.catalog_product_link_attribute_int.link_id,
m231_studentkare.catalog_product_link_attribute_int.value
)
SELECT
m231_studentkare_live_22112019.catalog_product_link_attribute_int.value_id,
m231_studentkare_live_22112019.catalog_product_link_attribute_int.product_link_attribute_id,
m231_studentkare_live_22112019.catalog_product_link_attribute_int.link_id,
m231_studentkare_live_22112019.catalog_product_link_attribute_int.value
FROM m231_studentkare_live_22112019.catalog_product_link_attribute_int
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_link_attribute_int.value_id = m231_studentkare_live_22112019.catalog_product_link_attribute_int.value_id,
m231_studentkare.catalog_product_link_attribute_int.product_link_attribute_id = m231_studentkare_live_22112019.catalog_product_link_attribute_int.product_link_attribute_id,
m231_studentkare.catalog_product_link_attribute_int.link_id = m231_studentkare_live_22112019.catalog_product_link_attribute_int.link_id,
m231_studentkare.catalog_product_link_attribute_int.value = m231_studentkare_live_22112019.catalog_product_link_attribute_int.value;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
