SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_product_link_attribute
(
m231_studentkare.catalog_product_link_attribute.product_link_attribute_id,
m231_studentkare.catalog_product_link_attribute.link_type_id,
m231_studentkare.catalog_product_link_attribute.product_link_attribute_code,
m231_studentkare.catalog_product_link_attribute.data_type
)
SELECT
m231_studentkare_live_22112019.catalog_product_link_attribute.product_link_attribute_id,
m231_studentkare_live_22112019.catalog_product_link_attribute.link_type_id,
m231_studentkare_live_22112019.catalog_product_link_attribute.product_link_attribute_code,
m231_studentkare_live_22112019.catalog_product_link_attribute.data_type
FROM m231_studentkare_live_22112019.catalog_product_link_attribute
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_product_link_attribute.product_link_attribute_id = m231_studentkare_live_22112019.catalog_product_link_attribute.product_link_attribute_id,
m231_studentkare.catalog_product_link_attribute.link_type_id = m231_studentkare_live_22112019.catalog_product_link_attribute.link_type_id,
m231_studentkare.catalog_product_link_attribute.product_link_attribute_code = m231_studentkare_live_22112019.catalog_product_link_attribute.product_link_attribute_code,
m231_studentkare.catalog_product_link_attribute.data_type = m231_studentkare_live_22112019.catalog_product_link_attribute.data_type;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
