<?php

/**
 * Block title
 */
$blockTitle = $block->getTitle();
$helper     = $this->helper('Magento\Catalog\Helper\Output');
$product    = $block->getProduct();

/**
 * Function of class Magento\Catalog\Block\Product\View\Attribute
 * Ref: vendor/magento/module-catalog/view/frontend/templates/product/view/attributes.phtml
 */
$attributesInfo = $block->getAdditionalData();

$attribute_codes = [
    'sale'                   => 'Is on sale',
    'text_area_attr'         => 'Other Information',
    'test'                   => 'Short Information',
    'custom_tag'             => 'Category Type',
    'climate'                => 'Favorable Climate',
    'country_of_manufacture' => 'Manufacturer Country',
    'custom_comment'         => 'Notes from manufacturer',
    'featured_product'       => 'Is Featured',
    'media_gallery'          => 'Default Media',
    'configtierprices_disabled' => 'configtierprices_disabled',
];

$tr = '';
foreach ($attribute_codes as $attribute_code => $attribute_label) {
    $attribute_value = $block->escapeHtml($product->getData($attribute_code));
    $attribute_label = $block->escapeHtml(__($attribute_label));

    if (in_array($attribute_code, array_keys($attributesInfo))) {
        if (empty($attribute_label)) {
            $attribute_label = $attributesInfo[$attribute_code]['label'];
        }

        if (isset($attributesInfo[$attribute_code]['value']) &&
            $attributesInfo[$attribute_code]['value']) {
            $attribute_value = $attributesInfo[$attribute_code]['value'];

            /**
             * Text editor content display
             */
            if (in_array($attribute_code, ['custom_comment'])) {
                $altered_attr_code_txt = str_replace([' ', '_', '-'], ' ', strtolower($attribute_code));
                $propertyMethod = str_replace(' ', '', 'get'.ucwords($altered_attr_code_txt));

                $attribute_value = $helper->productAttribute($product, $product->$propertyMethod(), $attribute_code);
            }
        }
    }

    /**
     * Default media gallery display
     */
    if (in_array($attribute_code, ['media_gallery'])) {
        $default_media = [];

        foreach ($attribute_value as $value) {
            foreach ($value as $vl) {
                if ($vl[2] == 'image') {
                    $alt_text = !empty($vl[7]) ? 'alt="'.$vl[7].'"' : '';
                    $mediaUrl = str_replace('default/', '', $block->getBaseUrl()).'pub/media/catalog/product';
                    $default_media[] = '<img src="'.$mediaUrl.$vl[1].'" '.$alt_text.' >';
                }
            }
        }
        $attribute_value = implode('<br >', $default_media);
    }

    /**
     * Boolean value display
     */
    if (($attribute_value === '1' || $attribute_value ===  '0'))  {
        $attribute_value = $attribute_value ? __('Yes') : __('No');
    }

    $tr .= <<< CONTENT
    <tr>
        <th class="col label" scope="row" width="10%">{$attribute_label}</th>
        <td class="col data" data-th="{$attribute_label}">{$attribute_value}</td>
    </tr>
CONTENT;
}

/**
 * Custom Attributes Display
 */
echo <<< CONTENT
<h3>{$blockTitle}</h3>
<div class="additional-attributes-wrapper table-wrapper">
    <table class="data table additional-attributes">
        <tbody>
        {$tr}
        </tbody>
    </table>
</div>
CONTENT;

/**
 * Product Description Display
 */
// echo $helper->productAttribute($product, $product->getDescription(), 'description');

// echo $helper->productAttribute($product, $product->getCountryOfManufacture(), 'country_of_manufacture');

/**
 * TinyMCE editor content display
 */
//$a = $helper->productAttribute($product, $product->getCustomComment(), 'custom_comment');

function print2($content = '') {
    echo '<pre>';
    print_r($content);
    echo '</pre>';
}
