SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.cataloginventory_stock_status_replica
(
m231_studentkare.cataloginventory_stock_status_replica.product_id,
m231_studentkare.cataloginventory_stock_status_replica.website_id,
m231_studentkare.cataloginventory_stock_status_replica.stock_id,
m231_studentkare.cataloginventory_stock_status_replica.qty,
m231_studentkare.cataloginventory_stock_status_replica.stock_status
)
SELECT
m231_studentkare_live_22112019.cataloginventory_stock_status_replica.product_id,
m231_studentkare_live_22112019.cataloginventory_stock_status_replica.website_id,
m231_studentkare_live_22112019.cataloginventory_stock_status_replica.stock_id,
m231_studentkare_live_22112019.cataloginventory_stock_status_replica.qty,
m231_studentkare_live_22112019.cataloginventory_stock_status_replica.stock_status
FROM m231_studentkare_live_22112019.cataloginventory_stock_status_replica
ON DUPLICATE KEY UPDATE
m231_studentkare.cataloginventory_stock_status_replica.product_id = m231_studentkare_live_22112019.cataloginventory_stock_status_replica.product_id,
m231_studentkare.cataloginventory_stock_status_replica.website_id = m231_studentkare_live_22112019.cataloginventory_stock_status_replica.website_id,
m231_studentkare.cataloginventory_stock_status_replica.stock_id = m231_studentkare_live_22112019.cataloginventory_stock_status_replica.stock_id,
m231_studentkare.cataloginventory_stock_status_replica.qty = m231_studentkare_live_22112019.cataloginventory_stock_status_replica.qty,
m231_studentkare.cataloginventory_stock_status_replica.stock_status = m231_studentkare_live_22112019.cataloginventory_stock_status_replica.stock_status;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
