<?php
/**
 * Copyright 2018 aheadWorks. All rights reserved.
 * See LICENSE.txt for license details.
 */

/* @var $block \Magento\Sales\Block\Adminhtml\Order\View\Info */

// @codingStandardsIgnoreFile
?>
<?php
    $order = $block->getOrder();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    try {
        $quote        = $objectManager->create('Magento\Quote\Api\CartRepositoryInterface')->get($order->getQuoteId());
        if ($quote->getData('timeslot_time') !== "") {
            if (strpos($quote->getData('timeslot_time'), '(') !== false) {
                $deliveryTime     = substr($quote->getData('timeslot_time'), 0, strpos($quote->getData('timeslot_time'), "("));
            } else {
                $deliveryTime = $quote->getData('timeslot_time');
            }
        }    
    } catch (Exception $e) {
        
    }
    $aw_delivery_date_from = $block->formatDate(
        $block->getOrderAdminDate($order->getData('aw_delivery_date_from')),
        \IntlDateFormatter::MEDIUM,
        true
    );
    $aw_delivery_date_to = $block->formatDate(
        $block->getOrderAdminDate($order->getData('aw_delivery_date_to')),
        \IntlDateFormatter::MEDIUM,
        true
    );
    $orderAdminDate = $block->formatDate(
        $block->getOrderAdminDate($order->getCreatedAt()),
        \IntlDateFormatter::MEDIUM,
        true
    );
    $orderStoreDate = $block->formatDate(
        $order->getCreatedAt(),
        \IntlDateFormatter::MEDIUM,
        true,
        $block->getTimezoneForStore($order->getStore())
    );
?>

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Order & Account Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */ ?>
            <?php if ($order->getEmailSent()):
                $email = __('The order confirmation email was sent');
            else:
                $email = __('The order confirmation email is not sent');
            endif; ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()): ?>
                        <?php echo $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?> (<span><?php echo $block->escapeHtml($email) ?></span>)
                    <?php else: ?>
                        <a href="<?php /* @noEscape */ echo $block->getViewUrl($order->getId()) ?>"><?php echo $block->escapeHtml(__('Order # %1', $order->getRealOrderId())) ?></a>
                        <span>(<?php echo $block->escapeHtml($email) ?>)</span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Order Date')) ?></th>
                        <td><?php /* @noEscape */ echo $orderAdminDate ?></td>
                    </tr>
                    <?php if ($orderAdminDate != $orderStoreDate):?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Order Date (%1)', $block->getTimezoneForStore($order->getStore()))) ?></th>
                            <td><?php /* @noEscape */ echo $orderStoreDate ?></td>
                        </tr>
                    <?php endif;?>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Order Status')) ?></th>
                        <td><span id="order_status"><?php echo $block->escapeHtml($order->getStatusLabel()) ?></span></td>
                    </tr>
                    <?php echo $block->getChildHtml(); ?>
                    <?php if ($block->isSingleStoreMode() == false):?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Purchased From')) ?></th>
                            <td><?php /* @noEscape */ echo $block->getOrderStoreName() ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($order->getRelationChildId()): ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Link to the New Order')) ?></th>
                            <td><a href="<?php /* @noEscape */ echo $block->getViewUrl($order->getRelationChildId()) ?>">
                                    <?php /* @noEscape */ echo $order->getRelationChildRealId() ?>
                                </a></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($order->getRelationParentId()): ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Link to the Previous Order')) ?></th>
                            <td><a href="<?php /* @noEscape */ echo $block->getViewUrl($order->getRelationParentId()) ?>">
                                    <?php /* @noEscape */ echo $order->getRelationParentRealId() ?>
                                </a></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($order->getRemoteIp() && $block->shouldDisplayCustomerIp()): ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Placed from IP')) ?></th>
                            <td><?php /* @noEscape */ echo $order->getRemoteIp(); echo($order->getXForwardedFor()) ? ' (' . $block->escapeHtml($order->getXForwardedFor()) . ')' : ''; ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($order->getGlobalCurrencyCode() != $order->getBaseCurrencyCode()): ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('%1 / %2 rate:', $order->getGlobalCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                            <td><?php /* @noEscape */ echo $order->getBaseToGlobalRate() ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($order->getBaseCurrencyCode() != $order->getOrderCurrencyCode()): ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('%1 / %2 rate:', $order->getOrderCurrencyCode(), $order->getBaseCurrencyCode())) ?></th>
                            <th><?php /* @noEscape */ echo $order->getBaseToOrderRate() ?></th>
                        </tr>
                    <?php endif; ?>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information kushal1">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Account Information')) ?></span>
                <div class="actions"><?php /* @noEscape */ echo $block->getAccountEditLink()?></div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Customer Name')) ?></th>
                        <td>
                            <?php if ($customerUrl = $block->getCustomerViewUrl()) : ?>
                                <a href="<?php /* @noEscape */ echo $customerUrl ?>" target="_blank">
                                    <span><?php echo $block->escapeHtml($order->getCustomerName()) ?></span>
                                </a>
                            <?php else: ?>
                                <?php echo $block->escapeHtml($order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Email')) ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($order->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($order->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Customer Group')) ?></th>
                            <td><?php /* @noEscape */ echo $groupName ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data):?>
                        <tr>
                            <th><?php echo $block->escapeHtml($data['label']) ?></th>
                            <td><?php echo $block->escapeHtml($data['value']) ?></td>
                        </tr>
                    <?php endforeach;
                    if($order->getShippingMethod() != "pickupatstore_pickupatstore_14")
                    {
                    if($order->getData('aw_delivery_date_from') != "" && $order->getData('aw_delivery_date_to') != "")
                    {
                    ?>
                        <?php if ($aw_delivery_date_from != "") : ?>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Delivery Date')) ?></th>
                                <td><?php echo date("M d, Y",strtotime($aw_delivery_date_from)); ?></td>
                            </tr>
                        <?php endif; ?>
                        <?php if ($deliveryTime != "" ) : ?>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Delivery Time')) ?></th>
                                <td><?php echo $deliveryTime; ?></td>
                            </tr>
                        <?php endif; 
                    }
                    }
                    ?>
                </table>
            </div>
        </div>
    </div>
</section>
<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Address Information')) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Billing Address')) ?></span>
                <div class="actions"><?php /* @noEscape */ echo $block->getAddressEditLink($order->getBillingAddress()); ?></div>
            </div>
            <address class="admin__page-section-item-content"><?php /* @noEscape */ echo $block->getFormattedAddress($order->getBillingAddress()) ?></address>
        </div>
        <?php if (!$block->getOrder()->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?php echo $block->escapeHtml(__('Shipping Address')) ?></span>
                    <div class="actions"><?php /* @noEscape */ echo $block->getAddressEditLink($order->getShippingAddress()); ?></div>
                </div>
                <address class="admin__page-section-item-content"><?php /* @noEscape */ echo $block->getFormattedAddress($order->getShippingAddress()) ?></address>
            </div>
        <?php endif; ?>
    </div>
</section>
<?php $orderNote = $order->getAwOrderNote(); ?>
<?php 
if (!(strpos($orderNote, 'js&u') !== false)) {
    
if ($orderNote): ?>
    <section class="admin__page-section order-note" style="display: none;">
        <div class="admin__page-section-title">
            <span class="title"><?php echo $block->escapeHtml(__('Customer Note')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <p><?php echo nl2br($block->escapeHtml($orderNote)) ?></p>
        </div>
    </section>
<?php endif; 

}
?>
