SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.salesrule_coupon_aggregated_updated
(
m231_studentkare.salesrule_coupon_aggregated_updated.id,
m231_studentkare.salesrule_coupon_aggregated_updated.period,
m231_studentkare.salesrule_coupon_aggregated_updated.store_id,
m231_studentkare.salesrule_coupon_aggregated_updated.order_status,
m231_studentkare.salesrule_coupon_aggregated_updated.coupon_code,
m231_studentkare.salesrule_coupon_aggregated_updated.coupon_uses,
m231_studentkare.salesrule_coupon_aggregated_updated.subtotal_amount,
m231_studentkare.salesrule_coupon_aggregated_updated.discount_amount,
m231_studentkare.salesrule_coupon_aggregated_updated.total_amount,
m231_studentkare.salesrule_coupon_aggregated_updated.subtotal_amount_actual,
m231_studentkare.salesrule_coupon_aggregated_updated.discount_amount_actual,
m231_studentkare.salesrule_coupon_aggregated_updated.total_amount_actual,
m231_studentkare.salesrule_coupon_aggregated_updated.rule_name
)
SELECT
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.id,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.period,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.store_id,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.order_status,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.coupon_code,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.coupon_uses,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.subtotal_amount,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.discount_amount,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.total_amount,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.subtotal_amount_actual,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.discount_amount_actual,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.total_amount_actual,
m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.rule_name
FROM m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated
ON DUPLICATE KEY UPDATE
m231_studentkare.salesrule_coupon_aggregated_updated.id = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.id,
m231_studentkare.salesrule_coupon_aggregated_updated.period = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.period,
m231_studentkare.salesrule_coupon_aggregated_updated.store_id = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.store_id,
m231_studentkare.salesrule_coupon_aggregated_updated.order_status = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.order_status,
m231_studentkare.salesrule_coupon_aggregated_updated.coupon_code = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.coupon_code,
m231_studentkare.salesrule_coupon_aggregated_updated.coupon_uses = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.coupon_uses,
m231_studentkare.salesrule_coupon_aggregated_updated.subtotal_amount = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.subtotal_amount,
m231_studentkare.salesrule_coupon_aggregated_updated.discount_amount = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.discount_amount,
m231_studentkare.salesrule_coupon_aggregated_updated.total_amount = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.total_amount,
m231_studentkare.salesrule_coupon_aggregated_updated.subtotal_amount_actual = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.subtotal_amount_actual,
m231_studentkare.salesrule_coupon_aggregated_updated.discount_amount_actual = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.discount_amount_actual,
m231_studentkare.salesrule_coupon_aggregated_updated.total_amount_actual = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.total_amount_actual,
m231_studentkare.salesrule_coupon_aggregated_updated.rule_name = m231_studentkare_live_22112019.salesrule_coupon_aggregated_updated.rule_name;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
