SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.catalog_url_rewrite_product_category
(
m231_studentkare.catalog_url_rewrite_product_category.url_rewrite_id,
m231_studentkare.catalog_url_rewrite_product_category.category_id,
m231_studentkare.catalog_url_rewrite_product_category.product_id
)
SELECT
m231_studentkare_live_22112019.catalog_url_rewrite_product_category.url_rewrite_id,
m231_studentkare_live_22112019.catalog_url_rewrite_product_category.category_id,
m231_studentkare_live_22112019.catalog_url_rewrite_product_category.product_id
FROM m231_studentkare_live_22112019.catalog_url_rewrite_product_category
ON DUPLICATE KEY UPDATE
m231_studentkare.catalog_url_rewrite_product_category.url_rewrite_id = m231_studentkare_live_22112019.catalog_url_rewrite_product_category.url_rewrite_id,
m231_studentkare.catalog_url_rewrite_product_category.category_id = m231_studentkare_live_22112019.catalog_url_rewrite_product_category.category_id,
m231_studentkare.catalog_url_rewrite_product_category.product_id = m231_studentkare_live_22112019.catalog_url_rewrite_product_category.product_id;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
