<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$ktplHelper = $this->helper('Ktpl\General\Helper\Category');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');

    if (!$_productCollection->count()) { ?>
        <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div><?php
    }else{  ?>
    
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    
    <?php
    $viewMode = 'list';
    $imageDisplayArea = 'category_page_list';    

    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php

                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <div class="product-tagline">
                            <?php echo $_product->getTagline(); ?>
                        </div><?php
                        $_product = $ktplHelper->getRatingSummary($_product);
                        $url = $_product->getProductUrl(). '#reviews';
                        $urlForm = $_product->getProductUrl(). '#review-form';
                        $_ratingSummary = $_product->getRatingSummary()->getRatingSummary();
                        $_reviewCount = $_product->getRatingSummary()->getReviewsCount(); ?>
                        <div class="product-reviews-summary short">
                            <div class="rating-summary">
                                <div title="<?php echo (int)$_ratingSummary; ?>%" class="rating-result">
                                    <span style="width:<?php echo (int)$_ratingSummary; ?>%"><span><?php echo (int)$_ratingSummary; ?>%</span></span>
                                </div>
                            </div>
                            <div class="reviews-actions"><?php
                            if ($_reviewCount > 0) { ?>
                                <div><a href="<?php echo $url; ?>"><?php echo __("Read Reviews (%1)",$_reviewCount); ?></div></a><?php
                            }else{ ?>
                                <div><a href="<?php echo $urlForm; ?>"><?php echo __("Be the first to review this product"); ?></a></div><?php
                            } ?>
                            </div>
                        </div>
                        <div class="attribute1">
                            <?php echo __($_product->getAttribute1()); ?>
                        </div>
                        
                        <?php 
                        $whyPayPrice = $_product->getWhyPay();
                        if ($_product->getTypeId() === \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE){
                            $groupedObj = $_product->getPriceInfo()->getPrice('final_price');
                            $minimalPrice = $groupedObj->getMinimalPrice()->getValue();
                            $formattedMinimalPrice = $priceHelper->currency($minimalPrice, true, false); ?>
  
                            <div class="price-box price-final_price" data-role="priceBox" data-product-id="<?= $_product->getId(); ?>" data-price-box="product-id-<?= $_product->getId(); ?>">
                                <div class="price-box">
                                    <p class="minimal-price">
                                        <span class="price-label"><?php echo __("As low as:"); ?></span>
                                        <span class="price-container tax weee">
                                            <span data-price-amount="<?= $minimalPrice; ?>" data-price-type="" class="price-wrapper ">
                                                <span class="price"><?= $formattedMinimalPrice; ?></span>
                                            </span>
                                        </span>
                                    </p>
                                </div>
                            </div><?php
                        }else{

                            $finalPrice = $_product->getPriceInfo()->getPrice('final_price')->getValue();
                            $regularPrice = $_product->getPriceInfo()->getPrice('regular_price')->getValue();
                            $formattedFinalPrice = $priceHelper->currency($finalPrice, true, false);
                            $formattedRegularPrice = $priceHelper->currency($regularPrice, true, false); 
                            $formattedWhyPayPrice = $priceHelper->currency($whyPayPrice, true, false); ?>

                            <?php if ($finalPrice < $regularPrice) { ?>
                                <div class="price-box price-final_price special-price-wrap" data-role="priceBox" data-product-id="<?= $_product->getId(); ?>" data-price-box="product-id-<?= $_product->getId(); ?>">
                                    <span class="old-price">
                                        <span class="price-container price-final_price tax weee">
                                            <span class="price-label"><?php echo __("Reg."); ?></span>
                                            <span id="old-price-<?= $_product->getId(); ?>" data-price-amount="<?= $regularPrice; ?>" data-price-type="oldPrice" class="price-wrapper ">
                                                <span class="price"><?= $formattedRegularPrice; ?></span>
                                            </span>
                                        </span>
                                    </span>
                                    <span class="special-price">
                                        <span class="price-container price-final_price tax weee">
                                                <span class="price-label"><?php echo __("SALE"); ?></span>
                                                <span id="product-price-<?= $_product->getId(); ?>" data-price-amount="<?= $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper ">
                                                    <span class="price"><?= $formattedFinalPrice; ?></span>
                                                </span>    
                                        </span>
                                    </span>
                                </div><?php
                            }elseif ($whyPayPrice > $regularPrice) { ?>
                                <div class="price-box price-final_price whypay-price-wrap" data-role="priceBox" data-product-id="<?= $_product->getId(); ?>" data-price-box="product-id-<?= $_product->getId(); ?>">
                                    <span class="old-price">
                                        <span class="price-container price-final_price tax weee">
                                            <span class="price-label"><?php echo __("Reg."); ?></span>
                                            <span id="old-price-<?= $_product->getId(); ?>" data-price-amount="<?= $regularPrice; ?>" data-price-type="oldPrice" class="price-wrapper ">
                                                <span class="price"><?= $formattedWhyPayPrice; ?></span>
                                            </span>
                                        </span>
                                    </span>
                                    <span class="regular-price">
                                        <span class="price-container price-final_price tax weee">
                                                <span id="product-price-<?= $_product->getId(); ?>" data-price-amount="<?= $finalPrice; ?>" data-price-type="finalPrice" class="price-wrapper ">
                                                    <span class="price"><?= $formattedFinalPrice; ?></span>
                                                </span>    
                                        </span>
                                    </span>
                                </div><?php
                            }else{ ?>
                                <div class="price-box price-final_price regular-price-wrap" data-role="priceBox" data-product-id="<?= $_product->getId(); ?>" data-price-box="product-id-<?= $_product->getId(); ?>">
                                    <span class="price-container price-final_price tax weee">
                                        <span id="product-price-<?= $_product->getId(); ?>" data-price-amount="<?= $finalPrice; ?>" class="price-wrapper ">
                                            <span class="price"><?= $formattedFinalPrice; ?></span>
                                        </span>
                                    </span>
                                </div><?php
                            } 
                        } ?>

                        <?php //echo $block->getProductPrice($_product);  ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <?php
                                                if ($_product->getTypeId() === \Magento\GroupedProduct\Model\Product\Type\Grouped::TYPE_CODE)
                                                { ?>
                                                <div class="product-option-<?= $_product->getId() ?> options-wrap"><?php
                                                    $childProductCollection = $_product->getTypeInstance()->getAssociatedProducts($_product);
                                                    $qtyOptions = array(); ?>
                                                    <select name="grouped_options" class="grouped_options" data-productid="<?= $_product->getId() ?>">
                                                        <option value=""><?php echo __("Choose"); ?></option><?php
                                                        foreach ($childProductCollection as $key => $options) {
                                                            $optionArray = explode($_product->getName(),$options->getName());
                                                            $optionName = array_pop($optionArray);
                                                            $qtyOptions[$key]["qty"] = $options->getQty(); 
                                                            $qtyOptions[$key]["id"] = $options->getId();
                                                            $formattedPrice = $priceHelper->currency($options->getFinalPrice(), true, false); ?>
                                                            <option value="<?php echo $options->getId(); ?>"><?php echo $optionName." ".$formattedPrice; ?></option>><?php    
                                                        } ?>
                                                    </select><?php

                                                    foreach ($qtyOptions as $key => $_item) { ?>
                                                        <input style="display: none;" type="number"
                                                           name="super_group[<?= /* @escapeNotVerified */ $_item['id'] ?>]"
                                                           id="super_group_<?= /* @escapeNotVerified */ $_item['id'] ?>"
                                                           data-selector="super_group[<?= /* @escapeNotVerified */ $_item['id'] ?>]"
                                                           value="<?= /* @escapeNotVerified */ $_item['qty'] * 1 ?>"
                                                           title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                                                           class="input-text qty grouped_qty"
                                                           data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                                           data-errors-message-box="#validation-message-box"/><?php
                                                    } ?>
                                                    
                                                    <button style="display: none;" type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary grouped_btn">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button><?php
                                                    foreach ($childProductCollection as $ky => $item) { ?>
                                                    <a href="javascript:void(0)" style="display: none;" data-post='<?php echo $wishlistHelper->getAddParams($item) ?>' class="action grouped_wishlist wishlist-link-<?= $item->getId(); ?>" data-action="add-to-wishlist"><span><?= __('Add to Wish List'); ?></span></a><?php
                                                    } ?>
                                                </div><?php
                                                }else{ ?>
                                                    <input type="number" name="qty">
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
                                                        <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                    </button>
                                                    <a href="javascript:void(0)" data-post='<?php  echo $wishlistHelper->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><span><?= __('Add to Wish List'); ?></span></a>
                                            <?php } ?>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            


                        </div>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
    <script type="text/javascript">
        require([
        'jquery'
        ], function ($) {
            $(document).ready(function(e){                
                $(".options-wrap .grouped_options").change(function(e){
                    var optionId = $(this).val();
                    var productId = $(this).attr("data-productid");
                    if (optionId) {
                        $(".product-option-"+productId+" .grouped_qty:not(#super_group_"+optionId+")").hide();
                        $("#super_group_"+optionId).show();
                        $(".product-option-"+productId+" .grouped_wishlist").hide();
                        $(".product-option-"+productId+" .grouped_btn, .wishlist-link-"+optionId).show();
                    }else{
                        $(".product-option-"+productId+" .grouped_qty, .product-option-"+productId+" .grouped_btn, .product-option-"+productId+" .grouped_wishlist").hide();
                    }
                });
            });
        });
    </script>
    <?php
}