SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.sales_bestsellers_aggregated_daily
(
m231_studentkare.sales_bestsellers_aggregated_daily.id,
m231_studentkare.sales_bestsellers_aggregated_daily.period,
m231_studentkare.sales_bestsellers_aggregated_daily.store_id,
m231_studentkare.sales_bestsellers_aggregated_daily.product_id,
m231_studentkare.sales_bestsellers_aggregated_daily.product_name,
m231_studentkare.sales_bestsellers_aggregated_daily.product_price,
m231_studentkare.sales_bestsellers_aggregated_daily.qty_ordered,
m231_studentkare.sales_bestsellers_aggregated_daily.rating_pos
)
SELECT
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.period,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.store_id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.product_id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.product_name,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.product_price,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.qty_ordered,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.rating_pos
FROM m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily
ON DUPLICATE KEY UPDATE
m231_studentkare.sales_bestsellers_aggregated_daily.id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.id,
m231_studentkare.sales_bestsellers_aggregated_daily.period = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.period,
m231_studentkare.sales_bestsellers_aggregated_daily.store_id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.store_id,
m231_studentkare.sales_bestsellers_aggregated_daily.product_id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.product_id,
m231_studentkare.sales_bestsellers_aggregated_daily.product_name = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.product_name,
m231_studentkare.sales_bestsellers_aggregated_daily.product_price = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.product_price,
m231_studentkare.sales_bestsellers_aggregated_daily.qty_ordered = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.qty_ordered,
m231_studentkare.sales_bestsellers_aggregated_daily.rating_pos = m231_studentkare_live_22112019.sales_bestsellers_aggregated_daily.rating_pos;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
