SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.sales_bestsellers_aggregated_yearly
(
m231_studentkare.sales_bestsellers_aggregated_yearly.id,
m231_studentkare.sales_bestsellers_aggregated_yearly.period,
m231_studentkare.sales_bestsellers_aggregated_yearly.store_id,
m231_studentkare.sales_bestsellers_aggregated_yearly.product_id,
m231_studentkare.sales_bestsellers_aggregated_yearly.product_name,
m231_studentkare.sales_bestsellers_aggregated_yearly.product_price,
m231_studentkare.sales_bestsellers_aggregated_yearly.qty_ordered,
m231_studentkare.sales_bestsellers_aggregated_yearly.rating_pos
)
SELECT
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.period,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.store_id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.product_id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.product_name,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.product_price,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.qty_ordered,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.rating_pos
FROM m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly
ON DUPLICATE KEY UPDATE
m231_studentkare.sales_bestsellers_aggregated_yearly.id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.id,
m231_studentkare.sales_bestsellers_aggregated_yearly.period = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.period,
m231_studentkare.sales_bestsellers_aggregated_yearly.store_id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.store_id,
m231_studentkare.sales_bestsellers_aggregated_yearly.product_id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.product_id,
m231_studentkare.sales_bestsellers_aggregated_yearly.product_name = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.product_name,
m231_studentkare.sales_bestsellers_aggregated_yearly.product_price = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.product_price,
m231_studentkare.sales_bestsellers_aggregated_yearly.qty_ordered = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.qty_ordered,
m231_studentkare.sales_bestsellers_aggregated_yearly.rating_pos = m231_studentkare_live_22112019.sales_bestsellers_aggregated_yearly.rating_pos;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
