SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.sales_invoiced_aggregated_order
(
m231_studentkare.sales_invoiced_aggregated_order.id,
m231_studentkare.sales_invoiced_aggregated_order.period,
m231_studentkare.sales_invoiced_aggregated_order.store_id,
m231_studentkare.sales_invoiced_aggregated_order.order_status,
m231_studentkare.sales_invoiced_aggregated_order.orders_count,
m231_studentkare.sales_invoiced_aggregated_order.orders_invoiced,
m231_studentkare.sales_invoiced_aggregated_order.invoiced,
m231_studentkare.sales_invoiced_aggregated_order.invoiced_captured,
m231_studentkare.sales_invoiced_aggregated_order.invoiced_not_captured
)
SELECT
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.id,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.period,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.store_id,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.order_status,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.orders_count,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.orders_invoiced,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.invoiced,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.invoiced_captured,
m231_studentkare_live_22112019.sales_invoiced_aggregated_order.invoiced_not_captured
FROM m231_studentkare_live_22112019.sales_invoiced_aggregated_order
ON DUPLICATE KEY UPDATE
m231_studentkare.sales_invoiced_aggregated_order.id = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.id,
m231_studentkare.sales_invoiced_aggregated_order.period = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.period,
m231_studentkare.sales_invoiced_aggregated_order.store_id = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.store_id,
m231_studentkare.sales_invoiced_aggregated_order.order_status = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.order_status,
m231_studentkare.sales_invoiced_aggregated_order.orders_count = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.orders_count,
m231_studentkare.sales_invoiced_aggregated_order.orders_invoiced = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.orders_invoiced,
m231_studentkare.sales_invoiced_aggregated_order.invoiced = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.invoiced,
m231_studentkare.sales_invoiced_aggregated_order.invoiced_captured = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.invoiced_captured,
m231_studentkare.sales_invoiced_aggregated_order.invoiced_not_captured = m231_studentkare_live_22112019.sales_invoiced_aggregated_order.invoiced_not_captured;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
