SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.sales_bestsellers_aggregated_monthly
(
m231_studentkare.sales_bestsellers_aggregated_monthly.id,
m231_studentkare.sales_bestsellers_aggregated_monthly.period,
m231_studentkare.sales_bestsellers_aggregated_monthly.store_id,
m231_studentkare.sales_bestsellers_aggregated_monthly.product_id,
m231_studentkare.sales_bestsellers_aggregated_monthly.product_name,
m231_studentkare.sales_bestsellers_aggregated_monthly.product_price,
m231_studentkare.sales_bestsellers_aggregated_monthly.qty_ordered,
m231_studentkare.sales_bestsellers_aggregated_monthly.rating_pos
)
SELECT
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.period,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.store_id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.product_id,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.product_name,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.product_price,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.qty_ordered,
m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.rating_pos
FROM m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly
ON DUPLICATE KEY UPDATE
m231_studentkare.sales_bestsellers_aggregated_monthly.id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.id,
m231_studentkare.sales_bestsellers_aggregated_monthly.period = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.period,
m231_studentkare.sales_bestsellers_aggregated_monthly.store_id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.store_id,
m231_studentkare.sales_bestsellers_aggregated_monthly.product_id = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.product_id,
m231_studentkare.sales_bestsellers_aggregated_monthly.product_name = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.product_name,
m231_studentkare.sales_bestsellers_aggregated_monthly.product_price = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.product_price,
m231_studentkare.sales_bestsellers_aggregated_monthly.qty_ordered = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.qty_ordered,
m231_studentkare.sales_bestsellers_aggregated_monthly.rating_pos = m231_studentkare_live_22112019.sales_bestsellers_aggregated_monthly.rating_pos;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
