SET GLOBAL FOREIGN_KEY_CHECKS=0;

INSERT INTO m231_studentkare.sales_shipping_aggregated_order
(
m231_studentkare.sales_shipping_aggregated_order.id,
m231_studentkare.sales_shipping_aggregated_order.period,
m231_studentkare.sales_shipping_aggregated_order.store_id,
m231_studentkare.sales_shipping_aggregated_order.order_status,
m231_studentkare.sales_shipping_aggregated_order.shipping_description,
m231_studentkare.sales_shipping_aggregated_order.orders_count,
m231_studentkare.sales_shipping_aggregated_order.total_shipping,
m231_studentkare.sales_shipping_aggregated_order.total_shipping_actual
)
SELECT
m231_studentkare_live_22112019.sales_shipping_aggregated_order.id,
m231_studentkare_live_22112019.sales_shipping_aggregated_order.period,
m231_studentkare_live_22112019.sales_shipping_aggregated_order.store_id,
m231_studentkare_live_22112019.sales_shipping_aggregated_order.order_status,
m231_studentkare_live_22112019.sales_shipping_aggregated_order.shipping_description,
m231_studentkare_live_22112019.sales_shipping_aggregated_order.orders_count,
m231_studentkare_live_22112019.sales_shipping_aggregated_order.total_shipping,
m231_studentkare_live_22112019.sales_shipping_aggregated_order.total_shipping_actual
FROM m231_studentkare_live_22112019.sales_shipping_aggregated_order
ON DUPLICATE KEY UPDATE
m231_studentkare.sales_shipping_aggregated_order.id = m231_studentkare_live_22112019.sales_shipping_aggregated_order.id,
m231_studentkare.sales_shipping_aggregated_order.period = m231_studentkare_live_22112019.sales_shipping_aggregated_order.period,
m231_studentkare.sales_shipping_aggregated_order.store_id = m231_studentkare_live_22112019.sales_shipping_aggregated_order.store_id,
m231_studentkare.sales_shipping_aggregated_order.order_status = m231_studentkare_live_22112019.sales_shipping_aggregated_order.order_status,
m231_studentkare.sales_shipping_aggregated_order.shipping_description = m231_studentkare_live_22112019.sales_shipping_aggregated_order.shipping_description,
m231_studentkare.sales_shipping_aggregated_order.orders_count = m231_studentkare_live_22112019.sales_shipping_aggregated_order.orders_count,
m231_studentkare.sales_shipping_aggregated_order.total_shipping = m231_studentkare_live_22112019.sales_shipping_aggregated_order.total_shipping,
m231_studentkare.sales_shipping_aggregated_order.total_shipping_actual = m231_studentkare_live_22112019.sales_shipping_aggregated_order.total_shipping_actual;

SET GLOBAL FOREIGN_KEY_CHECKS=1;
